baseurl = "https://hennessysview.com/"  # Include trailing slash
title = "Hennessy's View"
theme = "swift"
author = "Bill Hennessy"
copyright = "Copyright Â© 2003-2020, Right Press LLC & Bill Hennessy; all rights reserved."
canonifyurls = true
paginate = 8
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
rssLimit = 5

[params]
  ga_analytics = "UA-3826996-2" # google analytics ID e.g UA-116386578-1

  ga_verify = "google-site-verification=XfoRVS-X91PIqRi4b_ealPYbSv3Y76uBAu_ZLIXRt14"
  twitter = "@hennessystl" # twitter handle e.g @weru
  gab = "https://gab.com/whennessy"
  logo = "logo.gif"
  author = "Bill Hennessy" # default author
  image = "images/Hennessys-View-Photo.png" # used whenever a page image is not set
#  blogDir = "posts" # uncomment and edit to exclude normal pages ... see issue #57
  commento = true


