baseurl = "https://www.hennessysview.com/"  # Include trailing slash
title = "Hennessy's View"
theme = "swift"
author = "Bill Hennessy"
copyright = "Copyright Â© 2003-2020, Right Press LLC & Bill Hennessy; all rights reserved."
canonifyurls = true
paginate = 8
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
rssLimit = 5

[params]
  ga_analytics = "UA-3826996-2" # google analytics ID e.g UA-116386578-1

  ga_verify = "google-site-verification=XfoRVS-X91PIqRi4b_ealPYbSv3Y76uBAu_ZLIXRt14"
  twitter = "@hennessystl" # twitter handle e.g @weru
  logo = "logo.gif"
  author = "Bill Hennessy" # default author
  image = "images/Hennessys-View-Photo.png" # used whenever a page image is not set
  # blogDir = "posts" # uncomment and edit to exclude normal pages ... see issue #57
  commento = true
# [params.staticman]
#   endpoint = ""  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
#   gitProvider = "github"  # Either "github" or "gitlab"
#   username = "username"  # GitHub/GitLab user name
#   repository = "repo"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>